### PR TITLE
Bump version in CMakeLists.txt

### PR DESCRIPTION
**Pull request by climbfuji**
Bump version in CMakeLists.txt to 3.0.6-jedi (from 3.0.5 - slightly inconsistent format than the tags have). Tag should be 3.06-jedi ?

### CODE REVIEW

**Review by travissluka — APPROVED** [review]
eh, 3.0.6 is fine. bugfix, no new features,

**Comment by shlyaeva** [comment]
I am seeing
> -- git checkout develop @ /work/noaa/da/ashlyaev/jedi/code/jedi-bundle/gsw
CMake Error at /work/noaa/da/role-da/spack-stack/spack-stack-1.0.0-rc2/envs/skylab-1.0.0-gnu-10.2.0/install/gcc/10.2.0/ecbuild-3.6.5-synmrk4/share/ecbuild/cmake/ecbuild_project.cmake:106 (_project):
  VERSION "3.0.6-jedi" format invalid.
Call Stack (most recent call first):
  gsw/CMakeLists.txt:3 (project)

when I'm trying to do a fresh build :(

**Comment by shlyaeva** [comment]
I'll issue a fix -- call it 3.0.6

**Comment by climbfuji** [comment]
Sorry that was my fault.

**Comment by climbfuji** [comment]
@travissluka I'll need your help merging develop into master (if applicable), there are several conflicts and a very long commit history. Or do we create tags from develop for this repo?

**Comment by travissluka** [comment]
I think we don't want to use master, we never have apparently

**Comment by climbfuji** [comment]
Ok, so you want me to create the tag from develop?

**Comment by shlyaeva** [comment]
Looks like this is used in the latest soca tagged bundle:
```ecbuild_bundle( PROJECT gsw   GIT "https://github.com/jcsda/GSW-Fortran.git"  UPDATE TAG 1.0.0.soca )```
https://github.com/JCSDA/soca/blob/master/bundle/CMakeLists.txt#L57

but I don't see that tag on the internal one.

**Pull request merged**
