### PR TITLE
Different versions of gsw_mod_check_data.F90 for different compilers

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This is not the best solution, but it works for both older and newer Intel compilers, and for GNU. Basically duplicate the code in `modules/gsw_mod_check_data.F90` using CPP macros (`#ifdef`, `#else`, `#endif`). Requires an uppercase `.F90` suffix to enable automatic preprocessing.

### What problem does it fix? What new capability does it add?

Current version of `modules/gsw_mod_check_data.f90` does not compile with older Intel compilers. The previous version didn't compile with GNU. Newer Intel compilers are ok with both versions.

### Testing

Tested with GNU and Intel by @DJDavies2 and @climbfuji.

### Issue(s) addressed

n/a

## Acceptance Criteria (Definition of Done)

PR is merged

## Dependencies

none

## Impact

Any bundle/application using `GSW-Fortran`, especially soca.

### CODE REVIEW

**Comment by DJDavies2** [comment]
I have tested this branch here and it works for both Intel and Gnu.  Is it possible that it could be merged?

**Review by DJDavies2 — APPROVED** [review]

**Comment by climbfuji** [comment]
> No, we have removed GSW from the fv3-jedi CI so we need to test it manually.

It's in jedi-bundle, so in theory we can test it with ewok?

**Comment by ytremolet** [comment]
> > No, we have removed GSW from the fv3-jedi CI so we need to test it manually.
> 
> It's in jedi-bundle, so in theory we can test it with ewok?

It's used with soca. Could run the low res soca experiment?

**Comment by climbfuji** [comment]
> > > No, we have removed GSW from the fv3-jedi CI so we need to test it manually.
> > 
> > 
> > It's in jedi-bundle, so in theory we can test it with ewok?
> 
> It's used with soca. Could run the low res soca experiment?

Yes, ideally with Intel and GNU. Together with @DJDavies2 testing we should be good if that all works.

**Comment by hga007** [comment]
I tested the new **`gsw_mod_check_data.F90`** version and it works for two versions of **ifort** in a Linux cluster and my desktop Mac.  It is an ugly fix, but we hope that there are no issues with future versions of **gfortran** and **ifort**. Having a CPP option to distinguish between compilers in the explicit initialization of the GSW structures is reasonable to me.

**Review by hga007 — APPROVED** [review]

**Comment by yaswant** [comment]
> Hi, just to say I believe I've been experiencing the same issues - I can build JEDI to include GSW with our Gnu compiler but not Intel. I see this PR is marked as draft - can I test out your fix, or would you recommend I wait until you make some refinements?

@SusanSun17  This branch is compatible with hour mixed gnu/intel stack.  Until this gets merged, we can use this branch in jopa nightly and in the comparison suite.

**Comment by climbfuji** [comment]
I am testing it right now on Cheyenne with Skylab

**Comment by climbfuji** [comment]
I tested this with jedi-bundle on Cheyenne with GNU and OpenMPI, and the ctests for gsw passed successfully. We should merge this now.

**Pull request merged**
